# Week 11 - Earn-Back Points Assignment #1

These exercises are entirely optional, but they provide good practice. And you can use them to earn extra points toward your semester grade.  Each problem in this notebook can you earn you back up to 2 points.  There are key requirements, though. If your code does not following these rules, you will earn no points for your work.
* You MUST include docstrings that explain the purpose of your code.
* You MUST include at least 2 example tests in your docstrings for each function you write.
* You MUST run your docstrings within the notebook to show me your code and docstrings work correctly.
* You MUST submit your own individual work.  You may not collaborate with other students on these assignments.

There will be 4 assignments like this between now and the end of the semester, each with 4 problems, each worth 2 points, for a total of 32 points.

**If anything about the above rules is unclear, please message me on Canvas or via email**

---

## Earn-Back 1: Sunflower Health Plan Files

Sunflower Health Plan is one of Centene's state-specific health plans. If you aren't familiar with Centene, they are one of the largest healthcare maangement organizations the country and are headquartered here in St. Louis. Many of your colleagues from previous graduating classes now work at Centene. 

Sunflower Health Plan has posted links to two files on this page: https://www.sunflowerhealthplan.com/json.html

* https://www.sunflowerhealthplan.com/content/dam/centene/sunflower/json/KAPrintProviderDir_Prac.json
* https://www.sunflowerhealthplan.com/content/dam/centene/sunflower/json/KAPrintProviderDir_Prov.json

This entire problemset asks you to work with these files.

Your first step is to write a python function called **get_files(type)** where **type** is a string that contains one of two values: *practitioner* or *provider*.  Your function should download the correct file from the webpage above based on the string value passed to the function. The function should return the objects created by loading that JSON data.

**INPUT:** `'practitioneer'` or `'provider'`

**OUTPUT:** Python object based on the data from the appropriate file.


*Note that these files may take a minute for Python to download. They're big.*

In [14]:
import urllib.request, json
def get_files(file_type):
    """
    This function accepts two values: "practitioner" or "provider". Then downloads 
    the correct file from the webpage above based on the string value passed to the function. 
    The length of the practitioner data is 69292 and the length of the provider data is 22225
    
    >>> len(get_files('practitioner'))
    69292
    
    >>> len(get_files('provider'))
    22225
    
    >>> get_files('abcdef')
    File type was not found, enter: 'practitioner' or 'provider'
    """
    if file_type == 'practitioner':
        with urllib.request.urlopen("https://www.sunflowerhealthplan.com/content/dam/centene/sunflower/json/KAPrintProviderDir_Prac.json") as url:
            jason_file = json.load(url)
            return jason_file
        
    elif file_type == 'provider' :
        with urllib.request.urlopen("https://www.sunflowerhealthplan.com/content/dam/centene/sunflower/json/KAPrintProviderDir_Prov.json") as url:
            jason_file = json.load(url)
            return jason_file
        
    else :
        print("File type was not found, enter: 'practitioner' or 'provider'")

In [15]:
import doctest
doctest.run_docstring_examples(get_files, globals(), verbose=True)

Finding tests in NoName
Trying:
    len(get_files('practitioner'))
Expecting:
    69292
ok
Trying:
    len(get_files('provider'))
Expecting:
    22225
ok
Trying:
    get_files('abcdef')
Expecting:
    File type was not found, enter: 'practitioner' or 'provider'
ok


## Earn-Back 2: What is this Data?

No coding for this part, so no docstrings or tests are required.

Explain to in 2-3 sentences, what do you see in these files? If you can't make sense of it from a healthcare business perspective, just tell me what you see in techincal terms.

We have two json files, practitioner and provider. 

In the practitioner data we can see the list of informations about 69292 practitioners
such as, PRACTITIONER_ID, Name, location, OFFICEHOURS, SPECIALTY, etc. 
Primary key:PRACTITIONER_ID, Foreign key: PROVIDER_ID and LOCATION_ID

In the provider data we can see the list of informations about 22225 providers
such as, PROVIDER_ID, Name, location, OFFICEHOURS, SPECIALTY, etc. 
Primary key:PROVIDER_ID, Foreign key: LOCATION_ID

## Earn-Back 3: How many are closed on each Day of the Week

You'll see in the files a piece of information that tellsu us what the schedule is on every day of the week:

```json
'PROVIDER_ID': '387724',
 'LOCATION_ID': '626140',
 'NAME': 'Mercy Clinic Cardiology',
 'PROVIDER TYPE': 'GROUP PRACTICE',
 'NPI': '1215264817',
 'SPECIALTY': 'Multi-Specialty',
 'ADDRESS1': '3020 Saint Johns Boulevard',
 'ADDRESS2': 'Suite A1',
 'ADDRESS3': '',
 'CITY': 'Joplin',
 'STATE': 'MO',
 'ZIP': '64804',
 'COUNTY': 'Newton',
 'LATITUDE': '37.061',
 'LONGITUDE': '-94.536',
 'PHONE': '(417) 627-8566-(855) 420-7900',
 'AFTER HOUR PHONE': '',
 'FAX': '',
 'OFFICEHOURS_SU': 'Closed',
 'OFFICEHOURS_MO': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_TU': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_WE': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_TH': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_FR': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_SA': 'Closed',
 'HANDICAP ACCESS': 'N',
 'WEBSITE': 'www.mercy.net',
 'PRODUCT 1': 'GP',

```

Write a function called **closed_by_day(data)** that takes one parameter (the data that came out of the Provider or Practitioner download) and outputs a dictionary of how many practitioneres / providers are closed on each day:
```json
{
    "Sunday": 1401,
    "Monday": 2,
    ...etc...
```

In [21]:
def closed_by_day(data):
    """
    This function accepts two values: "practitioner" or "provider". Then downloads 
    the correct file from the webpage above based on the string value passed to the function.
    Returnes a dictionary of how many practitioneres / providers are closed on each day.
    
    >>> closed_by_day('provider')
    {'Sunday': 18505, 'Monday': 108, 'Tuesday': 53, 'Wednesday': 96, 'Thursday': 66, 'Friday': 259, 'Saturday': 17845}
    
     
    >>> closed_by_day('practitioner')
    {'Sunday': 66733, 'Monday': 188, 'Tuesday': 104, 'Wednesday': 135, 'Thursday': 110, 'Friday': 507, 'Saturday': 65286}
     
     
    
    """
    counter_m=0
    counter_tu=0
    counter_w=0
    counter_t=0
    counter_f=0
    counter_sa=0
    counter_su=0
    json_file = get_files(data)
    for value in json_file:
        mon=value.get('OFFICEHOURS_MO')
        tue=value.get('OFFICEHOURS_TU')
        wed=value.get('OFFICEHOURS_WE')
        thu=value.get('OFFICEHOURS_TH')
        fri=value.get('OFFICEHOURS_FR')
        sat=value.get('OFFICEHOURS_SA')
        sun=value.get('OFFICEHOURS_SU')
        if mon == 'Closed':
            counter_m +=1
        if tue == 'Closed':
            counter_tu +=1
        if wed == 'Closed':
            counter_w +=1
        if thu == 'Closed':
            counter_t +=1
        if fri == 'Closed':
            counter_f +=1
        if sat == 'Closed':
            counter_sa +=1
        if sun == 'Closed':
            counter_su +=1
    close_counter = {'Sunday':counter_su, 'Monday':counter_m, 'Tuesday':counter_tu, 'Wednesday':counter_w, 'Thursday':counter_t, 
                     'Friday':counter_f, 'Saturday': counter_sa}
    return close_counter
            
    
    

In [22]:
doctest.run_docstring_examples(closed_by_day, globals(), verbose=True)

Finding tests in NoName
Trying:
    closed_by_day('provider')
Expecting:
    {'Sunday': 18505, 'Monday': 108, 'Tuesday': 53, 'Wednesday': 96, 'Thursday': 66, 'Friday': 259, 'Saturday': 17845}
ok
Trying:
    closed_by_day('practitioner')
Expecting:
    {'Sunday': 66733, 'Monday': 188, 'Tuesday': 104, 'Wednesday': 135, 'Thursday': 110, 'Friday': 507, 'Saturday': 65286}
ok


In [17]:
closed_by_day('provider')

{'Sunday': 18505,
 'Monday': 108,
 'Tuesday': 53,
 'Wednesday': 96,
 'Thursday': 66,
 'Friday': 259,
 'Saturday': 17845}

In [18]:
closed_by_day('practitioner')

{'Sunday': 66733,
 'Monday': 188,
 'Tuesday': 104,
 'Wednesday': 135,
 'Thursday': 110,
 'Friday': 507,
 'Saturday': 65286}

## Earn-Back 4: Output to a file

Now, simply write a function named **to_csv(data, file)** that takes this summary view of information as a dictionary (the `data` parameter) and writes it out to a CSV file (the `file` parameter).

In [28]:
import pandas as pd
import os

In [49]:
def to_csv(data, file):
    """
    This function accepts two values: "practitioner" or "provider" for the first parameter(data). Then downloads 
    the correct file from the webpage above based on the string value passed to the function.
    Then saves file as "json_file.json" and read it as a pandas dataframe.
    Then save the file as csv with the given file name in the second parameter.
    Deletes "json_file.json" at the end. 
    
    The following code returnes name of first practitioner from csv file
    >>> to_csv('practitioner', 'prac') 
    None
    >>> pd.read_csv('prac.csv').iloc[0][4]
    'Matthew'
    
    The following code returnes name of first provider from csv file
    >>> to_csv('provider', 'prov')
    None
    >>> pd.read_csv('prov.csv').iloc[0][3]
    'Mercy Clinic Cardiology'
    
    """
    json_file = get_files(data)
    with open("json_file.json", "w") as outfile:
        json.dump(json_file, outfile)
    df=pd.read_json("json_file.json")
    df.to_csv(f'{file}.csv')
    os.remove("json_file.json")

In [50]:
doctest.run_docstring_examples(to_csv, globals(), verbose=True)

Finding tests in NoName
Trying:
    to_csv('practitioner', 'prac') 
Expecting:
    None
**********************************************************************
File "__main__", line 10, in NoName
Failed example:
    to_csv('practitioner', 'prac') 
Expected:
    None
Got nothing
Trying:
    pd.read_csv('prac.csv').iloc[0][4]
Expecting:
    'Matthew'


/opt/tljh/user/lib/python3.6/doctest.py:2107: DtypeWarning: Columns (9,50) have mixed types.Specify dtype option on import or set low_memory=False.
  runner.run(test, compileflags=compileflags)


ok
Trying:
    to_csv('provider', 'prov')
Expecting:
    None
**********************************************************************
File "__main__", line 16, in NoName
Failed example:
    to_csv('provider', 'prov')
Expected:
    None
Got nothing
Trying:
    pd.read_csv('prov.csv').iloc[0][3]
Expecting:
    'Mercy Clinic Cardiology'
ok


/opt/tljh/user/lib/python3.6/doctest.py:2107: DtypeWarning: Columns (17,35) have mixed types.Specify dtype option on import or set low_memory=False.
  runner.run(test, compileflags=compileflags)


## Submit your work to github in your week 11 folder by 11/18 11:59 PM